source 'https://rubygems.org'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use mysql as the database for Active Record
gem 'mysql2'

# ActiveModel extension that automatically strips all attributes of leading and trailing whitespace
gem 'strip_attributes'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma'

# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem 'jsbundling-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Zurb Foundation
gem 'autoprefixer-rails'
gem 'foundation-rails', '< 6.9.0.0' # higher versions currently result in a syntax error in foundation-rails-6.9.0.0/vendor/assets/scss/util/_util.scss # rubocop:disable Layout/LineLength

# Zurb Foundation for emails
gem 'inky-rb', require: 'inky'
gem 'premailer-rails'

# A pure Ruby PDF generation library
gem 'prawn'
gem 'prawn-svg'

# Font Awesome Icons
gem 'font-awesome-rails'

# A framework for building reusable, testable & encapsulated view components in Ruby on Rails.
gem 'view_component'

# Support for universally unique lexicographically sortable identifiers
gem 'ulid'

# Use Tester with source maps as compressor for JavaScript assets
gem 'sprockets_terser_with_source_maps'

# Provides hamlit generators for Rails. Hamlit = optimized HAML
gem 'haml-rails'

# Payment Processing
gem 'stripe'

# Send emails using Postmark
gem 'postmark-rails'

# Cloudflare Turnstile for Rails
gem 'cloudflare-turnstile-rails'

# Action caching for static content
gem 'actionpack-action_caching'

# Sentry error and performance logging
gem 'sentry-rails'
gem 'sentry-ruby'

# Handle the error "Invalid query parameters: invalid %-encoding"
gem 'rack-utf8_sanitizer'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Sass to process CSS
gem 'sassc-rails'

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem 'thruster', require: false

# Locked to prevent "LoadError: /lib64/libc.so.6: version `GLIBC_2.27' not found"
gem 'ffi', '1.17.0'
gem 'nokogiri', '< 1.18.0'

group :development do
  # Preview email in the default browser instead of sending it.
  gem 'letter_opener'
  # Code quality and linting packages
  gem 'haml_lint', require: false
  gem 'rubocop', require: false
  gem 'rubocop-capybara', require: false
  gem 'rubocop-i18n', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-minitest', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'scss_lint', require: false
  # Security vulnerability testing
  gem 'brakeman', require: false
  gem 'package-audit', require: false
end

group :test do
  # Retry test a few times if it fails the first time
  gem 'minitest-retry', require: false
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'
  gem 'selenium-webdriver'
  # Provides some addition controller test asserts
  gem 'rails-controller-testing'
  # A Ruby library for mocking and stubbing
  gem 'mocha'
  # A simple library for testing PDFs in Ruby
  gem 'pdf-reader'
end
