module Package
  module Audit
    module Npm
      class NpmMetaData
        REGISTRY_URL: String

        @packages: Array[Package]

        def initialize: (Array[Package]) -> void

        def fetch: -> Array[Package]

        private

        def update_meta_data: (Package, Hash[Symbol, untyped]) -> void

        def fetchable_packages: (Array[Package]) -> Array[Package]
      end
    end
  end
end
